name: Magicblock Daily Standup
on:
  schedule:
    - cron: '0 14 * * 2-4'
    
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: send standup message from file template
      uses: ./
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message_file: standup.txt
