name: Magicblock Bi-weekly Standup
on:
  schedule:
    - cron: '55 8 * * 1,3'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: send standup message from file template
      uses: ./
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message_file: standup_call.txt
